/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __CRAM_SAR_ROBOSHERLOCK_ALL_TYPES_H__
#define __CRAM_SAR_ROBOSHERLOCK_ALL_TYPES_H__

#include <cram_sar_robosherlock/types/type_definitions.h>


#endif /* __CRAM_SAR_ROBOSHERLOCK_ALL_TYPES_H__ */
