/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __CRAM_SAR_ROBOSHERLOCK_TYPE_DEFINITIONS_H__
#define __CRAM_SAR_ROBOSHERLOCK_TYPE_DEFINITIONS_H__


#endif /* __CRAM_SAR_ROBOSHERLOCK_TYPE_DEFINITIONS_H__ */
